/* Generated by Yosys 0.63+188 (git sha1 cede13a74, clang++ 18.1.8 -fPIC -O3) */

(* hdlname = "andgate" *)
(* top =  1  *)
(* src = "andgate.sv:2.1-10.10" *)
module andgate(a, b, y);
  (* src = "andgate.sv:3.18-3.19" *)
  input a;
  wire a;
  (* src = "andgate.sv:4.18-4.19" *)
  input b;
  wire b;
  (* src = "andgate.sv:5.18-5.19" *)
  output y;
  wire y;
  wire _0_;
  wire _1_;
  wire _2_;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/furz1000/olimex-gatemate/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:18.7-21.6" *)
  CC_LUT2 #(
    .INIT(4'h8)
  ) _3_ (
    .I0(_0_),
    .I1(_1_),
    .O(_2_)
  );
  (* keep = 32'd1 *)
  CC_IBUF _4_ (
    .I(a),
    .Y(_0_)
  );
  (* keep = 32'd1 *)
  CC_IBUF _5_ (
    .I(b),
    .Y(_1_)
  );
  (* keep = 32'd1 *)
  CC_OBUF _6_ (
    .A(_2_),
    .O(y)
  );
endmodule
